name: customer_segmentation
channels:
  - defaults
dependencies:
  - python=3.9
  - pandas
  - scikit-learn
  - matplotlib

  
You’ll get back the predicted cluster and its average profile.

---

## 📜 License

This project is open for academic and personal use.

---

## 🙌 Acknowledgments

- [Kaggle Contributor: Saurabh Badole](https://www.kaggle.com/code/saurabhbadole)
- UCI Machine Learning Repository
- scikit-learn & Python ecosystem

---

> Built with ❤️ using Python, Jupyter, and Machine Learning
